[project]
name = "vsp-llm-app"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clustering>=0.1.0",
    "gradio>=5.49.1",
    "mediapipe>=0.10.21",
    "numpy>=1.26.4",
    "omegaconf>=2.0.6",
    "opencv-python>=4.11.0.86",
    "torch>=2.5.1",
    "transformers>=4.49.0",
    "vsp-llm",
]

[tool.uv]
build-constraint-dependencies = [
    "opencv-python==4.11.0.86",
    "opencv-contrib-python==4.11.0.86",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
vsp-llm = { path = "../../../VSP-LLM" } # TOBEFIX
clustering = { path = "../../../VSP-LLM/clustering" } # TOBEFIX

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
