[project]
name = "vsp-llm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clustering>=0.1.0",
    "omegaconf>=2.0.6",
    "torch>=2.5.1",
    "transformers>=4.49.0",
    "vsp-llm",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
vsp-llm = { path = "../../../VSP-LLM" } # TOBEFIX
clustering = { path = "../../../VSP-LLM/clustering" } # TOBEFIX

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
