[project]
name = "fairseq_toolkit"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Hiroaki Ogasawara", email = "13391129+xhiroga@users.noreply.github.com" }
]

requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.10.1",
    "fairseq>=0.12.2",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "sentencepiece>=0.2.1",
    "torch<2.6.0",
    "transformers>=4.57.1",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
compare = "fairseq_toolkit.compare:main"
dump = "fairseq_toolkit.dump:main"
compare-lora = "fairseq_toolkit.compare_lora:main"

[tool.uv.sources]
fairseq = { git = "https://github.com/facebookresearch/fairseq.git", rev = "v0.12.2" }
