[project]
name = "fairseq_toolkit"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Hiroaki Ogasawara", email = "13391129+xhiroga@users.noreply.github.com" }
]

requires-python = ">=3.10"
dependencies = [
    "fairseq>=0.12.2",
    "torch>=2.8.0",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
compare = "fairseq_toolkit.compare:main"
dump = "fairseq_toolkit.dump:main"

[tool.uv.sources]
fairseq = { git = "https://github.com/facebookresearch/fairseq.git", rev = "v0.12.2" }
