[project]
name = "zavsr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "memray>=1.18.0",
    "transformers>=4.57.0",
    "zero-avsr",
]

[project.optional-dependencies]
webui = [
    "gradio>=5.49.1",
]

[tool.uv.sources]
zero-avsr = { git = "https://github.com/xhiroga/zero-avsr", rev = "packaged" }
