[project]
name = "zero_avsr_app"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe>=0.10.21",
    "memray>=1.18.0",
    "opencv-python>=4.8.1.78",
    "transformers>=4.57.0",
    "zero-avsr",
]

[project.optional-dependencies]
webui = [
    "gradio>=5.49.1",
]

[tool.uv.sources]
zero-avsr = { git = "https://github.com/xhiroga/zero-avsr", rev = "packaged" }

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
