[project]
name = "audio-visual-toolkit"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Hiroaki Ogasawara", email = "13391129+xhiroga@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.21",
    "numpy>=1.26.4",
    "opencv-python>=4.11.0.86",
    "pydantic>=2.11.9",
    "pytest>=8.4.2",
    "tqdm>=4.67.1",
]

[project.scripts]
crop-mouth = "audio_visual_toolkit.crop_mouth:main"
validate-label = "audio_visual_toolkit.validate_label:main"
mfa-aligned-to-label = "audio_visual_toolkit.mfa_aligned_to_label:main"
visualize-landmarks = "audio_visual_toolkit.visualize_landmarks:main"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "-vv --tb=short -s"
log_cli = true
log_cli_level = "INFO"
pythonpath = ["src"]
testpaths = ["tests"]
